### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by Soclatos** [nuance-dev/achico#1]
The latest version cannot save compressed files, clicking "save" has no effect

**Comment by Soclatos** [comment]
M2 pro mac

**Comment by nuance-dev** [comment]
Hi! I saw a bug where it wont save a file if the name already exists, doesn’t want to replace the existing file. Can you tell me if that’s the case or is this a different case? Ill review this

**Comment by nuance-dev** [comment]
This should be fixed on the latest release 👍
